project:
  type: website

website:
  title: "Hello, R!"
  description: "An R blog by Dan Chaltiel"
  site-url: https://danchaltiel.github.io/blog/
  repo-url: https://github.com/DanChaltiel/blog
  open-graph: true
  search: true
  twitter-card:
    creator: "@DanChaltiel"
    card-style: summary_large_image
  navbar:
    left:
      - icon: rss
        text: RSS
        href: index.xml
    right:
      - text: About me
        href: about.qmd
      - icon: github
        href: https://github.com/DanChaltiel
      - icon: bluesky
        href: https://bsky.app/profile/danchaltiel.bsky.social
      - icon: twitter
        href: https://x.com/DanChaltiel
      - icon: linkedin
        href: https://www.linkedin.com/in/dan-chaltiel-b3240895

format:
  html:
    theme: cosmo
    css: styles.css
    monofont: Fira Code, consolas, courier, monospace
    df-print: paged

